import java.util.ArrayList;

public class Event {
    // Required information
    private String title = "Untitled";
    private int[] date = new int[]{-1,-1,-1}; // Format: dd,mm,yyyy

    // Optional information
    private int[] time = new int[]{-1,-1}; // Format: mm,hh
    private String description = " ";
    private ArrayList<String> location = new ArrayList<>(); // Event can have multiple locations saved.
    private String category = "Uncategorized"; // Name of the category which the event is part of
    private int group = 0; // Priority of the category which the event is part of (for sorting)

    // 2D Event information
    private int[] dateEnd = new int[]{-1,-1,-1}; // Format: dd,mmy,yyy
    private int[] timeEnd = new int[]{-1,-1}; // Format: mm,hh

    public Event() {

    }

    // Minimal information constructor
    public Event(String title, int[] date) {
        this.title = title;
        this.date = date;
    }

    // Minimal information constructor
    public Event(String category, String title, int[] date) {
        this.category = category;
        this.title = title;
        this.date = date;
    }

    // All 1D information constructor
    public Event(String title, int[] date, int[] time, String description, ArrayList<String> location, String category, int group) {
        this.title = title;
        this.date = date;
        this.time = time;
        this.description = description;
        this.location = location;
        this.category = category;
        this.group = group;
    }

    // 2D Event constructor
    public Event(String title, int[] date, int[] time, String description, ArrayList<String> location, String category, int group, int[] dateEnd, int[] timeEnd) {
        this.title = title;
        this.date = date;
        this.time = time;
        this.description = description;
        this.location = location;
        this.category = category;
        this.group = group;
        this.dateEnd = dateEnd;
        this.timeEnd = timeEnd;
    }

    // Methods

    @Override
    public String toString() {
        String month = Main.intToMonth(date[1]);
        String endMonth = Main.intToMonth(dateEnd[1]);
        String timeString = "" + time[1];
        if (timeString.length() < 2) {
            timeString = "0" + timeString;
        }
        String timeEndString = "" + timeEnd[1];
        if (timeEndString.length() < 2) {
            timeEndString = "0" + timeEndString;
        }

        String s = "";
        s += "(" + category + ")"; // Category
        s += ", " + title; // Title
        s += ": " + month + " " + date[0] + ", " + date[2]; // Date
        if (dateEnd[0] != -1 && dateEnd != date) {
            s += " - " + endMonth + " " + dateEnd[0] + ", " + dateEnd[2]; // Ending Date (if exists)
        }
        if (time[0] != -1) {
            s += ", " + time[0] + ":" + timeString; // Time (if exists)
        }
        if (timeEnd[0] != -1) {
            s += " - " + timeEnd[0] + ":" + timeEndString; // Ending Time (if exists)
        }
        if (!location.isEmpty()) {
            s += ", " + location; // Location (if exists)
        }

        return s;
    }

    // Getters and Setters (generated by Intellij)
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public int[] getDate() {
        return date;
    }

    public void setDate(int[] date) {
        this.date = date;
    }

    public int[] getTime() {
        return time;
    }

    public void setTime(int[] time) {
        this.time = time;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public ArrayList<String> getLocation() {
        return location;
    }

    public void setLocation(ArrayList<String> location) {
        this.location = location;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public int getGroup() {
        return group;
    }

    public void setGroup(int group) {
        this.group = group;
    }

    public int[] getDateEnd() {
        return dateEnd;
    }

    public void setDateEnd(int[] dateEnd) {
        this.dateEnd = dateEnd;
    }

    public int[] getTimeEnd() {
        return timeEnd;
    }

    public void setTimeEnd(int[] timeEnd) {
        this.timeEnd = timeEnd;
    }
}
